@startuml AuthRegAD
start
:Ввод электронной почты;
:Ввод пароля;
:Создание профиля;
if (Аккаунт с такой почтой уже существует?) then (нет)
    :Завершение регистрации;
    :Перенаправление на главную страницу;
    stop
else (да)
    :Ошибка: На такой email уже зарегестрирован другой аккаутн;
    stop
endif

start
:Ввод электронной почты;
:Ввод пароля;
if (Проверка учетных данных) then (успех)
    :Перенаправление на главную страницу;
else (неудача)
    :Ошибка: Неверный email или пароль;
endif
stop
@enduml
