@startuml BoardAD
start

:Выбор действия (Создать, Редактировать, Удалить доску);
    if (Создание доски?) then (да)
        :Ввод названия доски;
        if (Доска успешно создана?) then (да)
            :Отображение новой доски;
        else (нет)
            :Ошибка: Не удалось создать доску;
            :Возврат к выбору действия на главную страницу;
            stop
        endif
    else (нет)
        if (Редактирование доски?) then (да)
            :Выбор доски для редактирования;
            :Ввод новых данных для доски;
            if (Изменения успешно сохранены?) then (да)
                :Обновление информации о доске;
            else (нет)
                :Ошибка: Не удалось сохранить изменения;
                :Возврат к выбору действия на главную страницу;
                stop
            endif
        else (нет)
            if (Удаление доски?) then (да)
                :Выбор доски для удаления;
                if (Подтверждение удаления?) then (да)
                    :Удаление доски;
                    :Сообщение об успешном удалении;
                else (нет)
                    :Отмена удаления;
                endif
            endif
        endif
    endif
:Возврат на главную страницу;
stop
@enduml
