@startuml InviteAD
start
:Выбор доски для приглашения;
:Выбор уровня доступа;
if (Редактор?) then (да)
    :Установка уровня доступа как "Редактор";
else (нет)
    :Установка уровня доступа как "Наблюдатель";
endif

:Генерация ссылки приглашения;

if (Ссылка успешно создана?) then (да)
    :Сохрание ссылки в буфере обмена;
else (нет)
    :Ошибка: Не удалось создать ссылку приглашения;
endif

stop
@enduml
