@startuml InviteAD
start
repeat
:Выбор доски для приглашения;
:Генерация ссылки приглашения;

if (Ссылка успешно создана?) then (да)
    :Сохрание ссылки в буфере обмена;
    :Возврат на страницу доски;
    stop
else (нет)
    :Ошибка: Не удалось создать ссылку приглашения;
    
endif
repeat while

@enduml
