@startuml usecaseDiagram
left to right direction

actor Редактор as Editor
actor СоздательДоски as Creator
package "Система управления проектами" {
    rectangle "Работать с пользователями" {
        usecase "Регистрация" as RegUC
        usecase "Авторизация" as AuthUC

        usecase "Редактировать профиль" as UserUC
            usecase "Сбросить пароль" as PassUC
            usecase "Изменить еmail" as EmailUC
    }

    rectangle "Работа с досками" {
        usecase "Работать с досками" as BoardUC
            usecase "Создать доску" as BoardCreateUC
            usecase "Изменить доску" as BoardEditUC
            usecase "Удалить доску" as BoardDeleteUC
    }

    rectangle "Работа с задачами" {
        usecase "Работать с задачами" as TaskUC
            usecase "Добавить задачу" as TaskCreateUC
            usecase "Редактировать задачу" as TaskEditUC
            usecase "Удалить задачу" as TaskDeletetUC
    }

    rectangle "Совместная работа" {
        usecase "Совместная работа" as СollaborationUC
            usecase "Пригласить пользователя на доску" as InviteUC
            usecase "Удалить пользователя из доски" as RemoveUC
    }


Creator .|> Editor

Editor -- RegUC
Editor -- AuthUC
Editor -- UserUC
    UserUC <.. PassUC: "include"
    UserUC <.. EmailUC: "include"

Editor -- TaskUC
    TaskUC ..> TaskCreateUC: "include"
    TaskUC ..> TaskEditUC: "include"
    TaskUC ..> TaskDeletetUC: "include"

Creator -- СollaborationUC
    СollaborationUC ..> InviteUC: "include"
    СollaborationUC <.. RemoveUC: "extend"

Creator -- BoardUC
    BoardUC ..> BoardCreateUC: "include"
    BoardUC ..> BoardEditUC: "include"
    BoardUC ..> BoardDeleteUC: "include"
}
@enduml
