@startuml UserManageAD
start
:Выбор доски для изменения доступа;
:Переход на страницу списка пользователей;
repeat
:Выбор пользователя;
:Исключение пользователя из доски;
     if (Пользователь успешно исключен?) then (да)
        :Уведомление об успешном исключении пользователя;
        :Возврат на страницу списка пользователей;
        stop
    else (нет)
        :Ошибка: Не удалось исключить пользователя;
    endif
repeat while
@enduml
