@startuml UserManageAD
start
:Выбор доски для изменения доступа;
:Выбор пользователя;

if (Изменить уровень доступа?) then (да)
    :Выбор нового уровня доступа;
  
    if (Передать права администратора?) then (да)
        :Установка уровня доступа как "Администратор";
    else (нет)
        if (Редактор?) then (да)
            :Установка уровня доступа как "Редактор";
        else (нет)
            :Установка уровня доступа как "Наблюдатель";
        endif
    endif

    if (Уровень доступа успешно изменен?) then (да)
        :Уведомление об успешном изменении доступа;
    else (нет)
        :Ошибка: Не удалось изменить уровень доступа;
    endif
else (нет)
    :Исключение пользователя из доски;

    if (Пользователь успешно исключен?) then (да)
        :Уведомление об успешном исключении пользователя;
    else (нет)
        :Ошибка: Не удалось исключить пользователя;
    endif
endif

stop
@enduml
